New listing
elizabethbott/MaizExchange pull request #6
Opened 2022-02-07 23:33 UTC by haasea

STILL NEED TO ADD STATE VARIABLES FOR EACH INDIVIDUAL INPUT

2022-02-09 21:58 UTC, JoelRummel commented
On mobile this screen could use some styling reworks:

![image0(13)](https://user-images.githubusercontent.com/18426418/153296878-72ea9fde-ccca-453e-8998-b7d9abcd5c5b.png)

2022-02-09 22:09 UTC, JoelRummel requested changes

2022-02-09 22:09 UTC, JoelRummel commented on src/screens/NewListingScreen.jsx
> +                        <View style={styles.categories}>
This whole view chunk gets copied and pasted three times, it should probably be extracted into its own reusable component.

No need to create a new file or anything - you can simply define it in this same file, above the `NewListingScreen` definition.

2022-02-09 22:09 UTC, JoelRummel commented on src/screens/NewListingScreen.jsx
> +    const [checked, setChecked] = React.useState('first');
Are you able to have the radio list start with all buttons un-checked instead of defaulting to ticket?

2022-02-09 22:09 UTC, JoelRummel commented on src/screens/NewListingScreen.jsx
> +                <View style={styles.container}>
These three views can all be collapsed into a single `ScrollView`. Scroll Views can be styled the same way regular views can.

2022-02-10 18:29 UTC, haasea commented
> On mobile this screen could use some styling reworks:
> 
> ![image0(13)](https://user-images.githubusercontent.com/18426418/153296878-72ea9fde-ccca-453e-8998-b7d9abcd5c5b.png)

It's weird because these radio buttons show up as checkmarks on IOS and I cannot change the background color on IOS. Should I pick a new radio button library?

2022-02-10 20:22 UTC, JoelRummel commented
You could do that, or you could write your own radio button component. Either way, I don't think the check mark is a serious issue. The bigger problem is that the content is being squeezed down into a little column in the middle of the screen instead of filling up the full screen width. A responsive design would be ideal, but since we're designing for mobile first, it's okay if it looks funky on a web browser for now.

Also make sure to pull main.

2022-02-16 20:59 UTC, merged